route:
  group_by: ['alertname', 'job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: alerts

receivers:
- name: alerts
  discord_configs:
  - webhook_url: <your_discord_webhook>
  slack_configs:
  - send_resolved: true
    text: "{{ .CommonAnnotations.description }}"
    channel: <#your_slack_channel_name>
    api_url: <your_slack_webhook>